invenio: 
  s3: 
    accessKeyId: aslalfkjsdnlhldl1
    secretAccessKey: aslalfkjsdnlhldl11
    region: aslalfkjsdnlhldl111
    s3EndpointUrl: aslalfkjsdnlhldl1111
cn-pg: 
  s3: 
    accessKeyId: aslalfkjsdnlhldl2
    secretAccessKey: aslalfkjsdnlhldl22
    region: aslalfkjsdnlhldl222
    s3EndpointUrl: aslalfkjsdnlhldl2222

