{{- if not .Values.s3.useExternalSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cn-pg.s3.secretname" . }} 
  namespace: {{ .Release.Namespace }}
  labels: {{ include "common.labels" . | indent 4 }}
data: 
  accessKeyId: {{ required "set S3 .Values.s3.accessKeyId" .Values.s3.accessKeyId | b64enc }} 
  secretAccessKey: {{ required "set S3 .Values.s3.secretAccessKey" .Values.s3.secretAccessKey | b64enc }} 
  region: {{ required "set S3 .Values.s3.region"  .Values.s3.region | b64enc }} 
  s3EndpointUrl: {{ required "set S3 .Values.s3.s3EndpointUrl"  .Values.s3.s3EndpointUrl | b64enc }}
{{- end -}}
