apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  test: true
  name: {{ include "common.fullname" . -}}-{{- required "\n\n.Values.certs.server.secretSuffix by default contains \"server-cert\"\n" .Values.certs.server.secretSuffix }}
  labels:
    {{- include "common.labels" . | indent 4 }}
spec:
  # Secret names are always required.
  secretName: {{ include "common.fullname" . -}}-{{- required "\n\n.Values.certs.server.secretSuffix by default contains \"server-cert\"\n" .Values.certs.server.secretSuffix }}
  secretTemplate:
    labels:
      cnpg.io/reload: ""
      {{- include "cn-pg.certs.server.secretTemplateLabels" . | indent 6 }}
      {{- include "common.labels" . | nindent 6 }}
  duration: {{ required "\n\nmissing certificate duration in .Values.certs.server.duration" .Values.certs.server.duration }}
  renewBefore: {{ required "\n\n missing cert's renew in .Values.certs.server.renewBefore" .Values.certs.server.renewBefore }}
  isCA: false
  usages:
    {{ range .Values.certs.server.usages }}
    - {{ . }}
    {{- end }}
  dnsNames:
  {{- include "cn-pg.certs.server.dnsNames" . | indent 2 }}
  issuerRef:
    kind: {{ required "\n`Issuer` or `ClusterIssuer`" .Values.certs.issuerRef.kind }}
    name: {{ required "\n Name of the issuer" .Values.certs.issuerRef.name }}
    group: {{ required "\n set to `cert-manager.io`" .Values.certs.issuerRef.group }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "common.fullname" . -}}-{{- required "\n\n.Values.certs.client.secretSuffix by default contains \"client-cert\"\n it looks secret suffix is missing for now" .Values.certs.client.secretSuffix }}
  labels:
    {{- include "common.labels" . | indent 4 }}
spec:
  # Secret names are always required.
  secretName: {{ include "common.fullname" . -}}-{{- required "\n\n.Values.certs.client.secretSuffix by default contains \"client-cert\"\n it looks secret suffix is missing for now" .Values.certs.client.secretSuffix }}
  secretTemplate:
    labels:
      cnpg.io/reload: ""
      {{- include "cn-pg.certs.client.secretTemplateLabels" . | indent 6 }}
      {{- include "common.labels" . | nindent 6 }}
  duration: {{ required "\n\nmissing certificate duration in .Values.certs.client.duration" .Values.certs.client.duration }}
  renewBefore: {{ required "\n\n missing cert's renew in .Values.certs.client.renewBefore" .Values.certs.client.renewBefore }}
  isCA: false
  commonName: {{ required  "\nmissing .Values.certs.client.commonName,\nrequired value is `streaming_replica`" .Values.certs.client.commonName }} 
  usages:
    {{ range .Values.certs.client.usages }}
    - {{ . }}
    {{- end }}
  issuerRef:
    kind: {{ required "\n`Issuer` or `ClusterIssuer`" .Values.certs.issuerRef.kind }}
    name: {{ required "\n Name of the issuer" .Values.certs.issuerRef.name }}
    group: {{ required "\n set to `cert-manager.io`" .Values.certs.issuerRef.group }}

