apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-%s" ( include "common.fullname" . ) "invenio-s3-keys" }} 
  namespace: {{ .Release.Namespace }}
  labels: {{ include "common.labels" . | indent 4 }}
data: 
  accessKeyId: {{ .Values.invenio.s3.accessKeyId | b64enc }} 
  secretAccessKey: {{ .Values.invenio.s3.secretAccessKey | b64enc }} 
  region: {{ .Values.invenio.s3.region | b64enc }} 
  s3EndpointUrl: {{ .Values.invenio.s3.s3EndpointUrl | b64enc }}
