{{- $password := include "common.password" (dict "key" "redisPassword" "pwlength" .Values.redis.passwordLength "svc" "redis"  "context" $ ) }}
{{- $redisServiceShortName := printf "%s-master" ( include "common.names.fullname" .Subcharts.redis ) }}
{{- $redisUser := printf "%s" .Values.redis.auth.username }}
apiVersion: v1
kind: Secret 
metadata:
  name: {{ printf "%s-%s" ( include "common.fullname" . ) "redis" }}
  namespace: {{ .Release.Namespace }}
  labels: {{ include "common.labels" . | indent 4 }}
data:
  redisPassword: {{ print $password | b64enc }}
  invenioCacheRedisHost: {{ printf ":%s@%s" $password $redisServiceShortName | b64enc }}
  invenioCacheRedisUrl: {{ printf "redis://:%s@%s:6379/0" $password $redisServiceShortName | b64enc }}
  invenioCeleryResultBackend: {{ printf "redis://:%s@%s:6379/2" $password $redisServiceShortName | b64enc }}
  invenioCommunitiesIdentitiesCacheRedisUrl: {{ printf "redis://:%s@%s:6379/4" $password $redisServiceShortName | b64enc }}
  invenioRatelimitStorageUrl: {{ printf "redis://:%s@%s:6379/3" $password $redisServiceShortName | b64enc }}
  invenioAccountsSessionRedisUrl: {{ printf "redis://:%s@%s:6379/1" $password $redisServiceShortName | b64enc }}
