{{- $rabbitmqPassword := include "common.password" (dict "key" "rabbitmqPassword" "pwlength" .Values.rabbitmq.passwordLength "svc" "rabbitmq" "context" $ ) }}
{{- $rabbitmqErlangCookie := include "common.password" (dict "key" "rabbitmqErlangCookie" "pwlength" .Values.rabbitmq.erlangCookieLength "svc" "rabbitmq" "context" $ ) }}
{{- $rabbitmqServiceShortName := printf "%s" ( include "common.names.fullname" .Subcharts.rabbitmq ) }}
{{- $rabbitmqUser := printf "%s" .Values.rabbitmq.auth.username }}

apiVersion: v1
kind: Secret 
metadata:
  name: {{ printf "%s-%s" ( include "common.fullname" . ) "rabbitmq" }}
  namespace: {{ .Release.Namespace }}
  labels: {{ include "common.labels" . | indent 4 }}
data:
  rabbitmqServiceShortName: {{ printf "%s" ( include "common.names.fullname" .Subcharts.rabbitmq ) | b64enc }}
  rabbitmqServiceLongName: {{ printf "%s.%s" ( include "common.names.fullname" .Subcharts.rabbitmq ) .Release.Namespace | b64enc }} 
  rabbitmqServiceFullName: {{ printf "%s.%s.%s" ( include "common.names.fullname" .Subcharts.rabbitmq ) .Release.Namespace "svc.cluster.local" | b64enc }} 
  rabbitmqUser: {{ print $rabbitmqUser | b64enc }}
  invenioCeleryBrokerUrl: {{ printf "amqp://%s:%s@%s:5672" $rabbitmqUser $rabbitmqPassword $rabbitmqServiceShortName  | b64enc }}
  rabbitmqPassword: {{ print $rabbitmqPassword | b64enc }}
  rabbitmqErlangCookie: {{ print $rabbitmqErlangCookie | b64enc }}
